### ISSUE TITLE
__filename is not defined

### ISSUE THREAD

**Issue by hvalette** [alexey2baranov/node-op-client#1]
Hello, 

I am not able to create the **EntityManager**. Once I run `new EntityManager({...})`, I got this error : 
```
index.js:6 Uncaught ReferenceError: __filename is not defined
    at Object.7tk/ (index.js:6)
    at __webpack_require__ (bootstrap:79)
    at Object.kU5X (index.js:1)
    at __webpack_require__ (bootstrap:79)
    at Object.UTLy (keypath-reducer.js:5)
    at __webpack_require__ (bootstrap:79)
    at Object.IxXd (set.js:1)
    at __webpack_require__ (bootstrap:79)
    at Object.LA/w (Abstract.js:6)
    at __webpack_require__ (bootstrap:79)
```

I am on **Angular 11.1.1**

Any Idea ?

**Comment by alexey2baranov** [comment]
Very strange. If you look into code , then you don.t see any `__filename` into it.

https://github.com/alexey2baranov/node-op-client/blob/4531c98df49595fdf0ed1f1a064623e9295cd904/src/EntityManager/EntityManager.ts#L23

It works on Vue.js. Unfortulally i don.t know Angular. But maybe if you share test code, i can help you.

**Comment by hvalette** [comment]
Thanks for the response.
I  just called this in a component initialization (same as _created_ for vuejs) : 
```typescript
import { EntityManager } from 'op-client';

...

ngOnInit() {
    const em = new EntityManager({
      baseUrl: 'http://localhost:4200',
      oauthOptions: {
        clientId: '...',
        clientSecret: '...',
      },
      createLogger: () => console,
    });
  }
```
I can see that in the readme example, you are importing the dependencies from '../src' and not from 'op-client'

**Comment by tatahnoellimnyuy** [comment]
please will you mind improving on documentation thank you

**Comment by hvalette** [comment]
> please will you mind improving on documentation thank you 

I do not have the time to work on that for the moment, I could give the lib a try with vuejs in the future.
